#!/bin/sh

if [ $(find test_suite 2>/dev/null | tail -n +2 | wc -l) = "0" ]
then
    wget http://www.hnng.moe/stuff/test_suite_20180515.tar.xz \
        || exit 1
    tar xf test_suite_20180515.tar.xz || exit 1
else
    echo "using existing test_suite"
fi
