#!/bin/sh

dir="$(dirname "$0")"
if command -v realpath 2>&1 >/dev/null; then
  wdir="$(realpath "$dir")"
else
  wdir="$dir"
fi
olddir="$(pwd)"
cd "$wdir" || exit $?

url="$(cat ./suite_url)"

if [ $(find test_suite 2>/dev/null | tail -n +2 | wc -l) = "0" ]; then
  curl -LO "$url" || exit $?
  tar xf "$(basename $url)" || exit $?
else
  echo "using existing test_suite"
fi

cd "$olddir"
