#!/bin/sh

dir="$(dirname "$0")"
wdir="$(realpath "$dir")"
olddir="$(pwd)"
cd "$wdir" || exit $?

url="https://github.com/Francesco149/oppai-ng/releases/download/2.2.0-test/test_suite_2019-02-09.tar.gz"

if [ $(find test_suite 2>/dev/null | tail -n +2 | wc -l) = "0" ]; then
  curl -LO "$url" || exit $?
  tar xf "$(basename $url)" || exit $?
else
  echo "using existing test_suite"
fi

cd "$olddir"
