#!/bin/sh

#docker run --rm -v $(dir):/tmp \
#    oppai/alpine:x86-latest-stable \
#    sh -c "apk add --update musl-dev gcc git xz; cd /tmp; ./release"

dir=$(dirname $0)
dir=$(readlink -f $dir)
prevdir=$(pwd)
cd $dir
for d in $dir/docker/*; do
    docker run --rm -v $dir:/tmp oppai-ng:$(basename $d)
done
cd $prevdir
